# dashboard
ACTIVITIES_PER_PAGE           = 5
RECOMMENDED_PEOPLE_PER_PAGE   = 1
RECOMMENDED_PROJECTS_PER_PAGE = 1


# events index page
EVENTS_PER_PAGE_IN_INDEX      = 2

# projects index page
PROJECTS_PER_PAGE_IN_INDEX    = 3