# dashboard
ACTIVITIES_PER_PAGE           = 5
RECOMMENDED_PEOPLE_PER_PAGE   = 5
RECOMMENDED_PROJECTS_PER_PAGE = 2
RECOMMENDED_EVENTS_PER_PAGE   = 2


# events index page
EVENTS_PER_PAGE_IN_INDEX      = 9

# projects index page
PROJECTS_PER_PAGE_IN_INDEX    = 9

# users index page
USERS_PER_PAGE_IN_INDEX    = 12