development:
  adapter: mysql2
  encoding: utf8
  database: filmzu_development
  username: root
  password: adminadmin
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: filmzu_test
  username: root
  password: adminadmin
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>